language: python
env:
    - PYTHON_VERSION=2.7
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - sudo apt-get install -y gdb
  - travis_retry conda create --yes -n env_name python=$PYTHON_VERSION pip nose flake8 coverage numpy httpretty
  - source activate env_name
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - travis_retry pip install .
before_script:
  - ulimit -c unlimited -S
script:
  - nosetests -v
  - flake8 qtp_biom setup.py scripts
after_success:
  - coveralls
after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
